parameters:
#    wiki_lanka_entity.example.class: WikiLanka\EntityBundle\Example

services:
#    wiki_lanka_entity.example:
#        class: %wiki_lanka_entity.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
