parameters:
#    wiki_lanka_facebook.example.class: WikiLanka\FacebookBundle\Example

services:
#    wiki_lanka_facebook.example:
#        class: %wiki_lanka_facebook.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
