parameters:
#    wiki_lanka_email.example.class: WikiLanka\EmailBundle\Example
    email: WikiLanka\EmailBundle\Controller\sendEmailController
services:
#    wiki_lanka_email.example:
#        class: %wiki_lanka_email.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

 email.send:
        class: "%email%"