parameters:
#    wiki_lanka_welcome.example.class: WikiLanka\WelcomeBundle\Example

services:
#    wiki_lanka_welcome.example:
#        class: %wiki_lanka_welcome.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
