parameters:
#    wiki_lanka_mobile.example.class: WikiLanka\MobileBundle\Example

services:
#    wiki_lanka_mobile.example:
#        class: %wiki_lanka_mobile.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
